import mongoose from 'mongoose';

const orderSchema = new mongoose.Schema(
  {
    medicine: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Medicine',
      required: true
    },
    supplier: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Supplier',
      required: true
    },
    quantity: {
      type: Number,
      required: true,
      min: 1
    },
    status: {
      type: String,
      enum: ['PENDING', 'APPROVED', 'REJECTED', 'FULFILLED'],
      default: 'PENDING'
    },
    autoGenerated: {
      type: Boolean,
      default: true
    },
    note: {
      type: String,
      default: ''
    }
  },
  { timestamps: true }
);

export const Order = mongoose.model('Order', orderSchema);
