export default function OrdersList({ orders }) {
  return (
    <section>
      <h3>Reorder Requests</h3>
      <div className="table-wrap">
        <table>
          <thead>
            <tr>
              <th>Medicine</th>
              <th>Supplier</th>
              <th>Quantity</th>
              <th>Status</th>
              <th>Type</th>
            </tr>
          </thead>
          <tbody>
            {orders.map((order) => (
              <tr key={order._id}>
                <td>{order.medicine?.name || 'N/A'}</td>
                <td>{order.supplier?.name || 'N/A'}</td>
                <td>{order.quantity}</td>
                <td>{order.status}</td>
                <td>{order.autoGenerated ? 'Auto' : 'Manual'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}
