import { Order } from '../models/Order.js';
import { Supplier } from '../models/Supplier.js';

const computeReorderQuantity = (medicine) => {
  const gap = medicine.minimumThreshold * 2 - medicine.quantityInStock;
  return gap > 0 ? gap : medicine.minimumThreshold;
};

export const triggerAutoReorderIfNeeded = async (medicine) => {
  if (medicine.quantityInStock >= medicine.minimumThreshold) {
    if (medicine.pendingOrder) {
      medicine.pendingOrder = false;
      await medicine.save();
    }
    return null;
  }

  const existingPendingOrder = await Order.findOne({
    medicine: medicine._id,
    status: 'PENDING'
  });

  if (existingPendingOrder) {
    medicine.pendingOrder = true;
    await medicine.save();
    return existingPendingOrder;
  }

  const fallbackSupplier = await Supplier.findOne();
  const selectedSupplier = medicine.supplier || fallbackSupplier?._id;

  if (!selectedSupplier) {
    console.warn(`Low stock warning for ${medicine.name}. No supplier available for auto reorder.`);
    return null;
  }

  const order = await Order.create({
    medicine: medicine._id,
    supplier: selectedSupplier,
    quantity: computeReorderQuantity(medicine),
    status: 'PENDING',
    autoGenerated: true,
    note: `Auto-generated reorder: stock (${medicine.quantityInStock}) below threshold (${medicine.minimumThreshold}).`
  });

  medicine.pendingOrder = true;
  await medicine.save();

  console.log(
    `[REORDER-SIMULATION] Created order ${order._id} for medicine ${medicine.name} from supplier ${selectedSupplier}.`
  );

  return order;
};
