import { Order } from '../models/Order.js';

export const getOrders = async (_req, res, next) => {
  try {
    const orders = await Order.find()
      .populate('medicine')
      .populate('supplier')
      .sort({ createdAt: -1 });
    res.json(orders);
  } catch (error) {
    next(error);
  }
};

export const createOrder = async (req, res, next) => {
  try {
    const order = await Order.create({ ...req.body, autoGenerated: false });
    const populated = await Order.findById(order._id).populate('medicine').populate('supplier');
    res.status(201).json(populated);
  } catch (error) {
    next(error);
  }
};

export const updateOrderStatus = async (req, res, next) => {
  try {
    const order = await Order.findByIdAndUpdate(
      req.params.id,
      { status: req.body.status },
      { new: true, runValidators: true }
    )
      .populate('medicine')
      .populate('supplier');

    if (!order) {
      return res.status(404).json({ message: 'Order not found.' });
    }

    res.json(order);
  } catch (error) {
    next(error);
  }
};
